
		services:
		  - type: web
		    name: medconnect-backend
		    env: java
		    buildCommand: "./mvnw clean install"  # For Maven projects
		    startCommand: "java -jar target/MedConnect-0.0.1-SNAPSHOT.jar"  # Modify if your JAR file name is different
		    envVars:
		      - key: SPRING_PROFILES_ACTIVE
		        value: prod  # If using profiles to indicate production
		     
		      # Add more environment variables as needed (e.g., MySQL credentials, etc.)
		    plan: free
		    region: oregon
			