services:
  - type: web
    name: medconnect-backend
    env: docker
    plan: free
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://localhost:3306/medconnect
      - key: SPRING_DATASOURCE_USERNAME
        value: root
      - key: SPRING_DATASOURCE_PASSWORD
        value: vedant@9565
      - key: TWILIO_ACCOUNT_SID
        value: AC205c5b896a18f289796752ef37a8ad86
      - key: TWILIO_AUTH_TOKEN
        value: 06a16dc64fe984e3a9bf57c97d52ce47
      - key: TWILIO_WHATSAPP_FROM
        value: whatsapp:+14155238886
