services:
  - type: web
    name: medconnect-backend
    env: docker
    plan: free
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://sql112.infinityfree.com:3306/if0_38757033_XXX
      - key: SPRING_DATASOURCE_USERNAME
        value: if0_38757033
      - key: SPRING_DATASOURCE_PASSWORD
        value: your_real_password_here
      - key: TWILIO_ACCOUNT_SID
        value: AC205c5b896a18f289796752ef37a8ad86
      - key: TWILIO_AUTH_TOKEN
        value: 06a16dc64fe984e3a9bf57c97d52ce47
      - key: TWILIO_WHATSAPP_FROM
        value: whatsapp:+14155238886
